version: '3.8'

services:
  stress-tester:
    build: .
    image: stress-tester:latest
    environment:
      - URL=http://google.com
      - REQUESTS=1000
      - CONCURRENCY=10
    entrypoint: ["/stress-tester", "--url=${URL}", "--requests=${REQUESTS}", "--concurrency=${CONCURRENCY}"]
